### PR TITLE
[Template-X] Hide Block When 0 Template Exists

### PR DESCRIPTION
**Pull request by JingleH**
We actually have 0 free templates for it-IT. It should not crash now and show error messages to visitors. We need to integrate Lana and have PROD monitoring for handling this.

Test URLs:
- Before: https://stage--express--adobecom.hlx.page/it/express/templates/flyer?lighthouse=on
- After: https://enhance-error-handle-it-templates--express--adobecom.hlx.page/it/express/templates/flyer?lighthouse=on
- Also after: https://enhance-error-handle-it-templates--express--adobecom.hlx.page/fr/express/?lighthouse=on

### CODE REVIEW

**Review by qiyundai — APPROVED** [review]

**Review by qiyundai — APPROVED** [review]

**Review by vhargrave — COMMENTED** [review]
I like the more defensive code on the placeholders ! 
Unfortunately the fallback text is all in english now. I don't think that's a great experience for our Italian users.
image

**Review by qiyundai — DISMISSED** [review]

**Comment by JingleH** [comment]
> I like the more defensive code on the placeholders ! Unfortunately the fallback text is all in english now. I don't think that's a great experience for our Italian users. image

Hi @vhargrave that is because no fallback locale was authored on IT pages. That English "oops" is the ultimate error message that should never ever be seen by visitors, as it indicates one of two scary things: 1. either a misauthored page goes live, or 2. the API is down. I think authors have added EN as a backup language for IT already so you should be seeing some generic templates on that link now. Nevertheless, to take care of the scary thing 1, I just added an ultimate fallback that should only fail when the API is down. We can localize that "oops" message in the future so even in scary thing 2, we shows reasonable messages. Thanks!

**Review by vhargrave — COMMENTED** [review]
Do we want to add a backup for the sort icons as well since we're covering these edge cases?
image

**Comment by JingleH** [comment]
> Do we want to add a backup for the sort icons as well since we're covering these edge cases? image

@vhargrave We were waiting for authors to update those localized sheets, but you had a good point that if we're already checking defensively, why not also give them some backup values. So I've copied those values from EN sheets into the code. Thanks!

**Review by qiyundai — APPROVED** [review]

**Comment by JingleH** [comment]
Although we do need to think about that not every authoring errors should have EN fallback though... sometimes a more salient error is easier to notice and fix before getting published, compared to code-level fallback that makes sure things always look okay but harder to notice. Something worth thinking about and maybe come up with a long-term strategy @vhargrave @qiyundai

**Comment by vhargrave** [comment]
> 

@JingleH that's true 👍

**Review by vhargrave — APPROVED** [review]
looks good!

**Pull request merged**
