### PR TITLE
Context template ckg

### PR DESCRIPTION
**Pull request by qiyundai**
This PR will retire CKG ID. We should see slight performance gain with one less sheet fetched. We should also see a lot less search pills as the new SEO pages without CKG ID will start to get matched at link list generation.

Resolves: [MWPW-137813](https://jira.corp.adobe.com/browse/MWPW-137813)

Test URLs:
- Before: https://stage--express--adobecom.hlx.page/express/templates/flyer?martech=off
- After: https://context-template-ckg--express--adobecom.hlx.page/express/templates/flyer?martech=off

### CODE REVIEW

**Comment by vhargrave** [comment]
Sent a direct message to Ravali & Sandilya today with Jingle & AG in CC
image

**Comment by vhargrave** [comment]
Issues were only occuring with taiwanese locale. This is being fixed by Ravali and then we can merge. I've asked today for feedback once Ravali has made this change

**Comment by qiyundai** [comment]
This is technically working now but some of the translations are different from our currently live version and can be a little off.

For example, the/tw/express/templates/flyer/dog pill on TW flyer page is now literally "Dog Flyers" rather than a more contextual "Flyers for missing dogs". (that said, the templates on the page is more like a general "pet related flyers". Neither "dog flyers" nor "Flyers for missing dogs" seems relevant to the actual content on the page)

The French page is also using an entirely different word for flyers (Dépliant).

Besides these, this is more or less acceptable. We get to reduce many lines in the template-ckg.js and removes one word mapping sheet fetch.

**Comment by qiyundai** [comment]
Update: The localization is currently handled by Adobe localization team. The Browse API team has a pipeline which consumes English pill names and returns the corresponding locale. As of now we are taking the results from this pipeline as-is and sending it back to the page to display.

**Review by vhargrave — APPROVED** [review]
looks good

**Review by JingleH — APPROVED** [review]

**Pull request merged**
