### PR TITLE
Breadcrumbs on for all

### PR DESCRIPTION
**Pull request by qiyundai**
*record scratch noise*

Given the new approach we discussed, this PR changes entirely how we author our breadcrumbs:

- Each hub page will need their own breadcrumbs base fragment authored here: [Breadcrumbs Fragment Folder](https://adobe.sharepoint.com/sites/adobecom/Express/Forms/AllItems.aspx?cid=3bf49379%2Dda97%2D4e20%2D9c4d%2D9ee0fb61115d&FolderCTID=0x012000DFEFB1E554C8C7408F4AA2DB25274737&id=%2Fsites%2Fadobecom%2FExpress%2Fwebsite%2Fexpress%2Ffragments%2Fbreadcrumbs&viewid=73aad62a%2D4c17%2D4a4f%2Db7ff%2Da7ab0f21a421). I've created a create-base file as an example.
- We'll need to add the `breadcrumbs-base` metadata to all the pages needing a breadcrumbs.
- we can use `breadcrumbs = off` metadata to turn the breadcrumbs off for a specific page.

We can now retire the breadcrumbs placeholder rows in placeholders sheet. They are techincally replaced by the base fragments

We are going to control our own breadcrumb's authoring too so we no longer rely on feds to localize 'Home' crumb (it was achievable before this new approach too but since we are doing authoring work already we might as well take this chance and stop using feds 'Home' crumb)

I would recommend merging the authoring work of this one with the one required for https://github.com/adobecom/express/pull/498

Resolves: [MWPW-136647](https://jira.corp.adobe.com/browse/MWPW-136647)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/drafts/qiyundai/create/create-flyer?martech=off
- Before: https://main--express--adobecom.hlx.page/drafts/qiyundai/create/create-hub?martech=off
- After: https://breadcrumbs-all--express--adobecom.hlx.page/drafts/qiyundai/create/create-flyer?martech=off
- After: https://breadcrumbs-all--express--adobecom.hlx.page/drafts/qiyundai/create/create-hub?martech=off

### CODE REVIEW

**Comment by qiyundai** [comment]
Adding a do not merge to wait for feds team content update finish

**Comment by vhargrave** [comment]
@qiyundai do we want to close this PR and take the different approach we discussed on Monday? (Using the metadata with a breadcrumbBase & short title)

**Comment by qiyundai** [comment]
> @qiyundai do we want to close this PR and take the different approach we discussed on Monday? (Using the metadata with a breadcrumbBase & short title)

I did some discovery with @AaronAtkinson this morning, combining what we heard yesterday in the meeting, It sounds like the process for us to use the milo global navigation breadcrumbs is:
- author `base breadcrumbs` fragment for each hub pages (second breadcrumb)
- add code to translate `short-title` to `breadcrumbs-page-title` before breadcrumbs generation

That said, it's only feasible to do this once we actually migrate to using the Milo global navigation, which is still a bit ways to go (Q1 - Q2 2024), right? Or are we at the point we can start the work already?

**Comment by vhargrave** [comment]
> > @qiyundai do we want to close this PR and take the different approach we discussed on Monday? (Using the metadata with a breadcrumbBase & short title)
> 
> I did some discovery with @AaronAtkinson this morning, combining what we heard yesterday in the meeting, It sounds like the process for us to use the milo global navigation breadcrumbs is:
> 
> * author `base breadcrumbs` fragment for each hub pages (second breadcrumb)
> * add code to translate `short-title` to `breadcrumbs-page-title` before breadcrumbs generation
> 
> That said, it's only feasible to do this once we actually migrate to using the Milo global navigation, which is still a bit ways to go (Q1 - Q2 2024), right? Or are we at the point we can start the work already?
> 
> Personally I would love to align to the milo way as soon as possible. That would also fix a lot of our Gnav CLS issue as we'd not need to refer to the placeholders anymore and we'll have way more control with the content living inside our sharepoint.

@qiyundai I think we should and can start now. Here's what I think we should do . 
1. In a separate milo college project, get a breadcrumb appearing with a base & rest.
2. Author these breadcrumbs just like that for the US local in express in fragments, defining them in the metadata, etc. 
3. Get our breadcrumb code to call the appropriate fragment that would get called in milo too, and construct the breadcrumb based upon the content of the fragment. This code will get removed after the migration. 

This approach will mean that the authoring work will have already been done by the authors and when we switch to milo, we won't need to invest any more authoring effort for the breadcrumbs. Sounds good?

**Comment by qiyundai** [comment]
> > > @qiyundai do we want to close this PR and take the different approach we discussed on Monday? (Using the metadata with a breadcrumbBase & short title)
> > 
> > 
> > I did some discovery with @AaronAtkinson this morning, combining what we heard yesterday in the meeting, It sounds like the process for us to use the milo global navigation breadcrumbs is:
> > 
> > * author `base breadcrumbs` fragment for each hub pages (second breadcrumb)
> > * add code to translate `short-title` to `breadcrumbs-page-title` before breadcrumbs generation
> > 
> > That said, it's only feasible to do this once we actually migrate to using the Milo global navigation, which is still a bit ways to go (Q1 - Q2 2024), right? Or are we at the point we can start the work already?
> > Personally I would love to align to the milo way as soon as possible. That would also fix a lot of our Gnav CLS issue as we'd not need to refer to the placeholders anymore and we'll have way more control with the content living inside our sharepoint.
> 
> @qiyundai I think we should and can start now. Here's what I think we should do .
> 
> 1. In a separate milo college project, get a breadcrumb appearing with a base & rest.
> 2. Author these breadcrumbs just like that for the US local in express in fragments, defining them in the metadata, etc.
> 3. Get our breadcrumb code to call the appropriate fragment that would get called in milo too, and construct the breadcrumb based upon the content of the fragment. This code will get removed after the migration.
> 
> This approach will mean that the authoring work will have already been done by the authors and when we switch to milo, we won't need to invest any more authoring effort for the breadcrumbs. Sounds good?

I think this makes sense. Just to be sure because I feel like I might be imagining things wrong in my head: it sounds like the new breadcrumbs we are building will become a seperate piece of element on the page outside of the feds gnav's scope. And we'll have to append the rendered breadcrumbs to the gnav?

**Comment by vhargrave** [comment]
> > > > @qiyundai do we want to close this PR and take the different approach we discussed on Monday? (Using the metadata with a breadcrumbBase & short title)
> > > 
> > > 
> > > I did some discovery with @AaronAtkinson this morning, combining what we heard yesterday in the meeting, It sounds like the process for us to use the milo global navigation breadcrumbs is:
> > > 
> > > * author `base breadcrumbs` fragment for each hub pages (second breadcrumb)
> > > * add code to translate `short-title` to `breadcrumbs-page-title` before breadcrumbs generation
> > > 
> > > That said, it's only feasible to do this once we actually migrate to using the Milo global navigation, which is still a bit ways to go (Q1 - Q2 2024), right? Or are we at the point we can start the work already?
> > > Personally I would love to align to the milo way as soon as possible. That would also fix a lot of our Gnav CLS issue as we'd not need to refer to the placeholders anymore and we'll have way more control with the content living inside our sharepoint.
> > 
> > 
> > @qiyundai I think we should and can start now. Here's what I think we should do .
> > 
> > 1. In a separate milo college project, get a breadcrumb appearing with a base & rest.
> > 2. Author these breadcrumbs just like that for the US local in express in fragments, defining them in the metadata, etc.
> > 3. Get our breadcrumb code to call the appropriate fragment that would get called in milo too, and construct the breadcrumb based upon the content of the fragment. This code will get removed after the migration.
> > 
> > This approach will mean that the authoring work will have already been done by the authors and when we switch to milo, we won't need to invest any more authoring effort for the breadcrumbs. Sounds good?
> 
> I think this makes sense. Just to be sure because I feel like I might be imagining things wrong in my head: it sounds like the new breadcrumbs we are building will become a seperate piece of element on the page outside of the feds gnav's scope. And we'll have to append the rendered breadcrumbs to the gnav?

@qiyundai not quite . We'll add new fragments and put breadcrumb blocks in these fragments, just as if we're a milo project. We'll add a new breadcrumb.js & breadcrumb.css file to our code that does **nothing** to these blocks. In the fragment word docs we'll add breadcrumb blocks just like they'd be added in milo. We then add metadata configurations for our pages, so that pages which should have breadcrumbs will have a link to the right fragment to load. On these pages we'll load the fragment, extract the content from the block, build up our breadcrumb array based upon the content from the block (base) and the short title. We then pass this breadcrumb info to the gnav object, as we've always done.

**Comment by qiyundai** [comment]
> > > > > @qiyundai do we want to close this PR and take the different approach we discussed on Monday? (Using the metadata with a breadcrumbBase & short title)
> 
> > > > 
> 
> > > > 
> 
> > > > I did some discovery with @AaronAtkinson this morning, combining what we heard yesterday in the meeting, It sounds like the process for us to use the milo global navigation breadcrumbs is:
> 
> > > > 
> 
> > > > * author `base breadcrumbs` fragment for each hub pages (second breadcrumb)
> 
> > > > * add code to translate `short-title` to `breadcrumbs-page-title` before breadcrumbs generation
> 
> > > > 
> 
> > > > That said, it's only feasible to do this once we actually migrate to using the Milo global navigation, which is still a bit ways to go (Q1 - Q2 2024), right? Or are we at the point we can start the work already?
> 
> > > > Personally I would love to align to the milo way as soon as possible. That would also fix a lot of our Gnav CLS issue as we'd not need to refer to the placeholders anymore and we'll have way more control with the content living inside our sharepoint.
> 
> > > 
> 
> > > 
> 
> > > @qiyundai I think we should and can start now. Here's what I think we should do .
> 
> > > 
> 
> > > 1. In a separate milo college project, get a breadcrumb appearing with a base & rest.
> 
> > > 2. Author these breadcrumbs just like that for the US local in express in fragments, defining them in the metadata, etc.
> 
> > > 3. Get our breadcrumb code to call the appropriate fragment that would get called in milo too, and construct the breadcrumb based upon the content of the fragment. This code will get removed after the migration.
> 
> > > 
> 
> > > This approach will mean that the authoring work will have already been done by the authors and when we switch to milo, we won't need to invest any more authoring effort for the breadcrumbs. Sounds good?
> 
> > 
> 
> > I think this makes sense. Just to be sure because I feel like I might be imagining things wrong in my head: it sounds like the new breadcrumbs we are building will become a seperate piece of element on the page outside of the feds gnav's scope. And we'll have to append the rendered breadcrumbs to the gnav?
> 
> 
> 
> @qiyundai not quite . We'll add new fragments and put breadcrumb blocks in these fragments, just as if we're a milo project. We'll add a new breadcrumb.js & breadcrumb.css file to our code that does **nothing** to these blocks. In the fragment word docs we'll add breadcrumb blocks just like they'd be added in milo. We then add metadata configurations for our pages, so that pages which should have breadcrumbs will have a link to the right fragment to load. On these pages we'll load the fragment, extract the content from the block, build up our breadcrumb array based upon the content from the block (base) and the short title. We then pass this breadcrumb info to the gnav object, as we've always done, but the huge advantage will be that when we move to milo the breadcrumbs will just keep working :) 

Ahh...good good. Thanks for the explanation!

**Comment by vhargrave** [comment]
Asked for update today: https://adobe-mwp.slack.com/archives/C04UH0M1CRG/p1702303319582819

**Comment by vhargrave** [comment]
sent another ping on slack

**Pull request closed without merging**
