### PR TITLE
[MWPW-128737-E] Bug fixes and enhancements on Create Marquee

### PR DESCRIPTION
**Pull request by williambsm**
Please always provide the [JIRA issue(s)](https://jira.corp.adobe.com/secure/RapidBoard.jspa?rapidView=34618) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix https://jira.corp.adobe.com/browse/MWPW-128737

Fixing the following issues
- The bottom spacing is now halved if there is no background.
- Images will now properly resize within the allowed space in the app.
- The block without variant will no longer break, and will now default to Image.
- The left-side editor is now also animated.

Test URLs:

- Before: 
  - [Full Screen Marquee (previous version)](https://main--express--adobecom.hlx.page/drafts/williambsm/mwpw-128737/fullscreen-marquee-previous?lighthouse=on)
- After: 
  - [Full Screen Marquee (Image variant)](https://mwpw-128737-e--express--adobecom.hlx.page/drafts/williambsm/mwpw-128737/fullscreen-marquee-v2?lighthouse=on)
  - [Full Screen Marquee (Image variant without background)](https://mwpw-128737-e--express--adobecom.hlx.page/drafts/williambsm/mwpw-128737/fullscreen-marquee-v2-without-background-with-row?lighthouse=on)
  - [Full Screen Marquee (Video variant)](https://mwpw-128737-e--express--adobecom.hlx.page/drafts/williambsm/mwpw-128737/fullscreen-marquee-v2-video-variant?lighthouse=on)

### CODE REVIEW

**Review by apganapa — APPROVED** [review]

**Review by toka1300 — COMMENTED** [review]
Looks good to me, except the padding on the bottom of the first preview link seems to be excessive and not showing on the other two?

**Review by toka1300 — APPROVED** [review]

**Review by qiyundai — APPROVED** [review]

**Review by vhargrave — CHANGES_REQUESTED** [review]
getting this weird bug 
image

**Comment by qiyundai** [comment]
> getting this weird bug image

The issue is technically fixed but for some reason I can't get the preview links to load the updated css...

**Comment by JingleH** [comment]
Looks like we already have a lot of approvals and the issue @vhargrave pointed out is fixed. I'm merging it to stage now.

**Pull request merged**
