### PR TITLE
[MWPW-143518] Marquee Pause Button Background

### PR DESCRIPTION
**Pull request by echen-adobe**
Describe your specific features or fixes

Makes the marquee pause button a solid color for visually impaired people.

 
"Sure! Keyboard works for the marquee, but the contrast of the button isn’t sufficient. I recommend putting a white background on the buttons so no matter what is in the background, it will always meet contrast.  I’m also curious as to why there are 2 different methods to pause gifs. This can be confusing to users since it isn’t consistent. (edited)
-Taryn Sikorski

Either spacebar or enter will work (both is ideal)  for pause when keyboard focus is on the button. You’re team won’t really have a choice about not changing the background color of the button because it’s a WCAG 2.1 AA failure, making it non-compliant.  They don’t have to make it black on white, but it must always meet 3:1 contrast.
"
 
Resolves: https://jira.corp.adobe.com/projects/MWPW/issues/MWPW-143518

Screenshot 2024-05-16 at 9 31 25 AM

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/
- After: https://accessibility-round-2--express--adobecom.hlx.page/express/

### CODE REVIEW

**Comment by JingleH** [comment]
can you add the ticket number and quickly check if designers can sign off on the button's new color?

**Comment by echen-adobe** [comment]
> can you add the ticket number and quickly check if designers can sign off on the button's new color?

I don't think we need the designers input since we are mandated to have the background color

**Comment by echen-adobe** [comment]
> can you add the ticket number and quickly check if designers can sign off on the button's new color?

Sure, I don't know who the designers are though. We will still need the background color but they could recommend a different color that meets 3:1 contrast

**Comment by JingleH** [comment]
> hen keyboard focus is on the button. You’re team won’t really have a choice about not changing the background color of the button because it’s a WCAG 2.1 AA failure, making it non-compliant. They don’t have to make it black on white, but it must al

Hi @echen-adobe, let's reach out to Abhi and Sean. I'm just checking just in case they'll want certain shades of grey rather than pure white plus this will affect branded pages like homepage

**Pull request closed without merging**
