### PR TITLE
[MWPW-132069] Steps How To Carousel - Color Page

### PR DESCRIPTION
**Pull request by qiyundai**
Please always provide the [JIRA issue(s)](https://jira.corp.adobe.com/secure/RapidBoard.jspa?rapidView=34618) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix [MWPW-132069](https://jira.corp.adobe.com/browse/MWPW-132069)

**Description:**
How To Steps build from scratch (renamed as Steps How To Carousel)
Currently the only version supported is Color page with SVG. We will be expanding the block for retrospective features existing on the old How To Steps Carousel

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/colors/red?lighthouse=on
- After: https://mwpw-132069--express--adobecom.hlx.page/express/colors/red?lighthouse=on

### CODE REVIEW

**Review by apganapa — APPROVED** [review]

**Review by redvelvet511 — CHANGES_REQUESTED** [review]
Ola, for responsiveness, between 600px - 980px, the left part of the carousel is being hidden/cut off on the side.

**Comment by qiyundai** [comment]
@vhargrave We will likely not prioritize this until after Project X GA. Do you think we should close this for now?

**Comment by vhargrave** [comment]
> @vhargrave We will likely not prioritize this until after Project X GA. Do you think we should close this for now?

@qiyundai Sure, just add a link to this closed PR as a comment on the task so we know we need to reopen it again

**Comment by qiyundai** [comment]
Closing for deprioritization

**Pull request closed without merging**
