### PR TITLE
New banner

### PR DESCRIPTION
**Pull request by kennethlum**
Describe your specific features or fixes

Resolves: [MWPW-155548](https://jira.corp.adobe.com/browse/MWPW-155548)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/drafts/kennethlum/banners-demo?lighthouse=on
- After: https://new-banner--express--adobecom.hlx.page/drafts/kennethlum/banners-demo?lighthouse=on

URL for testing:
- https://new-banner--express--adobecom.hlx.page/drafts/kennethlum/banners-demo?lighthouse=on

### CODE REVIEW

**Review by echen-adobe — COMMENTED** [review]
Hey @kennethlum , be sure to check with Sal on whether the white section of the banner is wide enough, other than that it looks good to me. I'll approve as soon as Sal says its good to go design wise.

**Comment by kennethlum** [comment]
> Hey @kennethlum , be sure to check with Sal on whether the white section of the banner is wide enough, other than that it looks good to me. I'll approve as soon as Sal says its good to go design wise.

hm, I think from the conversation, he meant when the window is, say 1100px wide, then the white portion is 1024px wide and that's fine. And then he said if the window is 1180px wide, keep the white part the same width, letting the left and right purple-ish border be wider.  Is that what you mean?

**Comment by qiyundai** [comment]
@kennethlum do you think you can add a unit test for the new variant? We already have it in our test library. You can just add a mock and check for only the added new lines. Thanks!

**Comment by kennethlum** [comment]
> @kennethlum do you think you can add a unit test for the new variant? We already have it in our test library. You can just add a mock and check for only the added new lines. Thanks!

oh let me check with Jingle whether he wants Haris to get his hands on writing some tests.

**Review by JingleH — APPROVED** [review]

**Review by echen-adobe — APPROVED** [review]

**Pull request merged**
