### PR TITLE
QA guide checklist logging + story selector

### PR DESCRIPTION
**Pull request by qiyundai**
Resolves: [MWPW-139772](https://jira.corp.adobe.com/browse/MWPW-139772) & [MWPW-140014](https://jira.corp.adobe.com/browse/MWPW-140014)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/colors/pink?martech=off
- After: https://qa-guide-checklist-logging--express--adobecom.hlx.page/express/colors/pink?martech=off

### CODE REVIEW

**Comment by qiyundai** [comment]
This is once again a little difficult to test. You can try loading your sidekick from this branch or test locally by adding devMode: true in the configs.json for sidekick.

**Review by JingleH — APPROVED** [review]

**Comment by AaronAtkinson** [comment]
Not sure who would make changes to this feature, but my testing on localhost didn't go well (it is very possible that I wasn't testing this properly)

After adding devMode to the sidekick's config.json, I was able to get the sidekick to show up with the QA Guide option, and it did open a new tab with the url param qaprogress=1, but that page never loaded.

By manually visiting a page with the url param, pages were loading as expected with the QA Guide pop up checklist displaying. However after checking all the boxes, the next button failed to bring me to the next page. I was able to trigger the next QA guide step by incrementing the url parameter myself.

By loading a page with qaprogress=11, I was able to get the QA Guide's final step to show up, which did seem to finish and send a submission. But the timestamp in the log file seems to not be a formatted date like the other entries are. I'm not sure if some changes were made to the logging logic between this PR and future QA Guide PRs that addressed the timestamp. 

As is right now, it appears to not be functioning properly to me. 

image

**Comment by AaronAtkinson** [comment]
As PR #518 is based off this PR, I'm wondering if there is anything in this that isn't included in #518 and if this can be closed.

**Comment by AaronAtkinson** [comment]
> Not sure who would make changes to this feature, but my testing on localhost didn't go well (it is very possible that I wasn't testing this properly)
> 
> After adding devMode to the sidekick's config.json, I was able to get the sidekick to show up with the QA Guide option, and it did open a new tab with the url param qaprogress=1, but that page never loaded.
> 
> By manually visiting a page with the url param, pages were loading as expected with the QA Guide pop up checklist displaying. However after checking all the boxes, the next button failed to bring me to the next page. I was able to trigger the next QA guide step by incrementing the url parameter myself.
> 
> By loading a page with qaprogress=11, I was able to get the QA Guide's final step to show up, which did seem to finish and send a submission. But the timestamp in the log file seems to not be a formatted date like the other entries are. I'm not sure if some changes were made to the logging logic between this PR and future QA Guide PRs that addressed the timestamp.
> 
> As is right now, it appears to not be functioning properly to me.
> 
> image

Just an update, it seems that somewhere in the development of this branch the stored date was changed from a formatted date to a plain timestamp. So this is not a bug, or any sort of unexpected behaviour. But possibly something that we should discuss as to whether we should revert to storing the timestamp in a more readable format.

**Comment by AaronAtkinson** [comment]
As PR #518 is based off this PR, I'm wondering if there is anything in this that isn't included in #518 and if this can be closed.

**Review by apganapa — APPROVED** [review]

**Pull request merged**
