### PR TITLE
Search term satellite tracking

### PR DESCRIPTION
**Pull request by qiyundai**
Added templates search term tracking with amplitude through satellite.
Event integrated:
search-inspire
view-search-results
select-template
select-load-more

Resolves: [MWPW-141738](https://jira.corp.adobe.com/browse/MWPW-141738)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/templates/
- After: https://search-term-satellite-tracking--express--adobecom.hlx.page/express/templates/

### CODE REVIEW

**Comment by qiyundai** [comment]
Keeping it in draft because we are blocked by the satellite team.

**Review by JingleH — APPROVED** [review]

**Comment by vhargrave** [comment]
@qiyundai this looks like a stale PR. can we close it?

**Comment by qiyundai** [comment]
It actually isn't stale for what I know 😅. It's just taking forever for the schema update to be accepted and this has just been waiting for that.

The conversation is happening here: https://adobe.enterprise.slack.com/archives/C06GS4EJURZ
and @JingleH might have a little more context around it.

**Comment by vhargrave** [comment]
> @vhargrave It actually isn't stale for what I know 😅. It's just taking forever for the schema update to be accepted and this has just been waiting for that.
> 
> The conversation is happening here: https://adobe.enterprise.slack.com/archives/C06GS4EJURZ and @JingleH might have a little more context around it.

ok 😅 👍  - I can't seem to access that slack thread, but that's fine. Hopefully this gets cleared up soon then.

**Review by echen-adobe — APPROVED** [review]

**Pull request merged**
