### PR TITLE
[MWPW-136149] CSS split for template X

### PR DESCRIPTION
**Pull request by qiyundai**
We could save the template X block from loading half of its 2800+ lines CSS file for specific variants. This PR could potentially make small visually breaking changes to the template X block so a through QA would be appreciated! (Yes, I'm doing that myself too! 😄)

Resolves: [MWPW-136149](https://jira.corp.adobe.com/browse/MWPW-136149)

Test URLs:
- Before: https://main--express--adobecom.hlx.page/express/templates/?martech=off
- After: https://mwpw-136149--express--adobecom.hlx.page/express/templates/?martech=off

### CODE REVIEW

**Review by vhargrave — CHANGES_REQUESTED** [review]
I love the initiative man! 
I do think this is going to make everything slower though unfortunately :( 
Every request we make is expensive and I'd rather have a slightly bigger CSS file than sending two css requests. The only big **but** is if we're not usually ever loading additional css (but we usually are right?)

Screenshot 2023-09-12 at 14 56 12

Screenshot 2023-09-12 at 14 56 18

**Comment by qiyundai** [comment]
> I love the initiative man! I do think this is going to make everything slower though unfortunately :( Every request we make is expensive and I'd rather have a slightly bigger CSS file than sending two css requests. The only big **but** is if we're not usually ever loading additional css (but we usually are right?)
> 
> Screenshot 2023-09-12 at 14 56 12
> 
> Screenshot 2023-09-12 at 14 56 18

Just did some reading on the subject and seems yeah it's doing more harm than good. It might be worth the investment if we only split out the horizontal part of it but still, it seems every css file causes at least 30ms to load and we are only saving 10ms with all these effort.

**Comment by JingleH** [comment]
Great discussion @qiyundai and @vhargrave ! I agree that modularization often gains maintainability at the cost of performance. And this applies not just for CSS but also our JS files. Without treeshaking, we either suffer with fewer big css/js files that's still growing as we are going to develop new template-x variants (the color one is coming), or we suffer with smaller files causing requiring more network requests. BTW I now think the performance gains of parsing smaller js/css files shouldn't matter hugely to us, because our js/css files are still within the kbs zone and not going to mbs zone and browsers these days parse fast. Still, I personally would vote for separating them for maintainability as this block is not an LCP block and on many pages it's used below the fold, but I tend to overdo these kinds of things so you folks should make the decision

**Comment by vhargrave** [comment]
> Great discussion @qiyundai and @vhargrave ! I agree that modularization often gains maintainability at the cost of performance. And this applies not just for CSS but also our JS files. Without treeshaking, we either suffer with fewer big css/js files that's still growing as we are going to develop new template-x variants (the color one is coming), or we suffer with smaller files causing requiring more network requests. BTW I now think the performance gains of parsing smaller js/css files shouldn't matter hugely to us, because our js/css files are still within the kbs zone and not going to mbs zone and browsers these days parse fast. Still, I personally would vote for separating them for maintainability as this block is not an LCP block and on many pages it's used below the fold, but I tend to overdo these kinds of things so you folks should make the decision

@JingleH fair - I completely understand that perspective too. From an architecture perspective I also prefer having code more modular and cleanly split up. 
Unfortunately, I can't be approving PRs at the moment if I see them negatively impacting our site speed in any way (At least not until we're back to 100). Imo every block needs to be written with the perspective that it might be LCP. My philosophy with code is : 
1. Make it work
2. Make it fast
3. Make it right

Right now we haven't fulfilled step two, and so I can't see us moving onto step three yet. 

@qiyundai How about we close this PR, but once our site performance is back in shape we reopen discussions like this to start improving our code design?

**Comment by qiyundai** [comment]
Deferred for when we are in a better position to talk about code design.

**Pull request closed without merging**
