### PR TITLE
[BUG FIX] Refactored templates.js page validation fix

### PR DESCRIPTION
**Pull request by qiyundai**
Please always provide the [JIRA issue(s)](https://jira.corp.adobe.com/secure/RapidBoard.jspa?rapidView=34618) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix no ticket

**Description:**
A quick correction in the refactored script to allow templates/default to be viewable in stage environment

**Test URLs:**
- Before: https://main--express--adobecom.hlx.page/express/templates/random?lighthouse=on
- After: https://fix-templates-validate--express--adobecom.hlx.page/express/templates/random?lighthouse=on

### CODE REVIEW

**Review by vhargrave — COMMENTED** [review]
@qiyundai why are we doing this? :)

**Comment by qiyundai** [comment]
> @qiyundai why are we doing this? :)

We used to have an issue where the authors can't preview the default page because it's not one of the pages authored in the metadata sheet. With the new LHS fix, we don't look through the sheet anymore and rely on the metadata title being properly populated or not to determine if the page is up for rendering. This fix bypasses that logic on stage environment so templates/default can be previewed.

**Review by vhargrave — APPROVED** [review]
ok, thanks for the explanation!

**Review by vhargrave — CHANGES_REQUESTED** [review]
can't we actually just check if some mandatory metadata is set for the page and if it's not then it's clearly a 404?

**Comment by qiyundai** [comment]
> 

It's doing that actually. We consider <title> as a mandatory metadata and it's the first in the head.
That said, I think we can probably just close this PR. The old main -> new main will introduce many new files and the templates.js will actually no longer exist.

**Pull request closed without merging**
